modLoader="javafml"
loaderVersion="[32,)"
license="MIT"

[[mods]]
    modId="dramaticdoors"
    version="1.16.5-1.4.0"
    displayName="Dramatic Doors"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dramatic-doors"
    issueTrackerURL="https://github.com/TheFizzWare/DramaticDoors/issues"
    authors="FizzWare"
    credits="Thanks to the creators of Minecraft and Forge."
    description='''
    Doors that are barely tall enough to fit your player ... ?
    Doors that suffocate you when you ride ol' Blackjack the horse through? Enderman discrimination? Seriously?
    ... PAH!!

    Can we not have intrigue?  Whatever happened to the tender grace and elegance of a nice tall door? Where is the drama?!?
    Here. I have it. And now you can too.

    Gone are the ways of the past - with the new Dramatic Doors mod!

    With the modern era of innovations comes a new door type: the tall door.
    These 3-block-high doors come in every vanilla variety;
    Oak, Spruce, Birch, Acacia, Dark Oak, Jungle, Iron, and now the new Nether Doors: Crimson and Warped!
    Craft one by putting 3 of the vanilla variant vertically in a crafting table.
    
    Now supports certain mods that add wood types!
    '''

[[dependencies.dramaticdoors]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[1.16.5,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="twilightforest"
    mandatory=false
    versionRange="[4.0.546,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="atmospheric"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="autumnity"
    mandatory=false
    versionRange="[2.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="bamboo_blocks"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="buzzier_bees"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="endergetic"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="environmental"
    mandatory=false
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="upgrade_aquatic"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="abundance"
    mandatory=false
    versionRange="[1.16.5-1.0.5,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="bayou_blues"
    mandatory=false
    versionRange="[1.16.5-1.0.5,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="enhanced_mushrooms"
    mandatory=false
    versionRange="[1.16.5-3.0.9,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="outer_end"
    mandatory=false
    versionRange="[0.2,)"
    ordering="AFTER"
    side="BOTH"